/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testjni_Nlib */

#ifndef _Included_com_example_testjni_Nlib
#define _Included_com_example_testjni_Nlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni_Nlib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_testjni_Nlib_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_testjni_Nlib
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_testjni_Nlib_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
